# Bank Marketing Dataset Schema Definition
# This schema defines expected structure, types, and constraints

dataset_name: bank_marketing_term_deposit
version: "1.0"
description: "Schema for UCI Bank Marketing dataset with term deposit subscription prediction"

columns:
  # Numerical columns
  age:
    type: integer
    nullable: false
    min_value: 18
    max_value: 100
    description: "Age of the client"

  balance:
    type: integer
    nullable: false
    min_value: -10000
    max_value: 200000
    description: "Average yearly balance in euros"

  day:
    type: integer
    nullable: false
    min_value: 1
    max_value: 31
    description: "Last contact day of the month"

  duration:
    type: integer
    nullable: false
    min_value: 0
    max_value: 5000
    description: "Last contact duration in seconds"

  campaign:
    type: integer
    nullable: false
    min_value: 1
    max_value: 100
    description: "Number of contacts performed during this campaign"

  pdays:
    type: integer
    nullable: false
    min_value: -1
    max_value: 1000
    description: "Number of days since client was last contacted (-1 means not contacted)"

  previous:
    type: integer
    nullable: false
    min_value: 0
    max_value: 300
    description: "Number of contacts before this campaign"

  # Categorical columns
  job:
    type: string
    nullable: false
    allowed_values:
      - "admin."
      - "blue-collar"
      - "entrepreneur"
      - "housemaid"
      - "management"
      - "retired"
      - "self-employed"
      - "services"
      - "student"
      - "technician"
      - "unemployed"
      - "unknown"
    description: "Type of job"

  marital:
    type: string
    nullable: false
    allowed_values:
      - "divorced"
      - "married"
      - "single"
    description: "Marital status"

  education:
    type: string
    nullable: false
    allowed_values:
      - "primary"
      - "secondary"
      - "tertiary"
      - "unknown"
    description: "Education level"

  default:
    type: string
    nullable: false
    allowed_values:
      - "yes"
      - "no"
    description: "Has credit in default?"

  housing:
    type: string
    nullable: false
    allowed_values:
      - "yes"
      - "no"
    description: "Has housing loan?"

  loan:
    type: string
    nullable: false
    allowed_values:
      - "yes"
      - "no"
    description: "Has personal loan?"

  contact:
    type: string
    nullable: false
    allowed_values:
      - "cellular"
      - "telephone"
      - "unknown"
    description: "Contact communication type"

  month:
    type: string
    nullable: false
    allowed_values:
      - "jan"
      - "feb"
      - "mar"
      - "apr"
      - "may"
      - "jun"
      - "jul"
      - "aug"
      - "sep"
      - "oct"
      - "nov"
      - "dec"
    description: "Last contact month of year"

  poutcome:
    type: string
    nullable: false
    allowed_values:
      - "failure"
      - "other"
      - "success"
      - "unknown"
    description: "Outcome of previous marketing campaign"

  # Target variable
  y:
    type: string
    nullable: false
    allowed_values:
      - "yes"
      - "no"
    description: "Has the client subscribed to a term deposit? (target variable)"

# Expected row count range
expected_row_count:
  min: 1000
  max: 50000

# Required columns (all must be present)
required_columns:
  - age
  - job
  - marital
  - education
  - default
  - balance
  - housing
  - loan
  - contact
  - day
  - month
  - duration
  - campaign
  - pdays
  - previous
  - poutcome
  - y
